### ISSUE TITLE
Scarcity issue

### ISSUE THREAD

**Issue by parsafaramarzi** [loot/loot#1130]
based on author description the plugin should be  right before bashed patch but loot puts the two modules after the bashed patch and also loot shows with a red background to use only one module but author said two is fine

**Comment by CurusKeel** [comment]
See loot/libloot#59 for more details, this appears to be an issue with the masterlist sorting in that library.

**Comment by Ortham** [comment]
As mentioned in the linked issue, the masterlist is trying to use a regex where an exact filename is needed, this isn't a problem with LOOT itself.

**Comment by CptMcSplody** [comment]
> As mentioned in the linked issue, the masterlist is trying to use a regex where an exact filename is needed, this isn't a problem with LOOT itself.

@Ortham Okay thanks, yeah my mistake, I've corrected it now.
@parsafaramarzi Can you update your masterlist and test again.
For the errors, make sure you only have one `Scarcity - x Loot Rarity.esp` and one `Scarcity - x Merchant Item Rarity.esp` installed. The install archive has several 
![image](https://user-images.githubusercontent.com/1944639/61578514-fec8f800-aaef-11e9-9942-07e4983a114f.png) options that are all installed by default.

**Comment by parsafaramarzi** [comment]
@CptMcSplody yes im aware ive set all other plugins hidden but issue still persists regarding the error 
![Capture](https://user-images.githubusercontent.com/53096076/61579196-97bf3980-ab17-11e9-8e75-989889c1a63b.JPG)

**Comment by parsafaramarzi** [comment]
maybe loot still thinks i have them enabled? like does loot distiguish a hidden and non-hidden plugin from eachother?

**Comment by CptMcSplody** [comment]
> maybe loot still thinks i have them enabled? like does loot distiguish a hidden and non-hidden plugin from eachother?

Yeah, that seems to be the cause, hidden files will still be flagged, 
the `.mohidden` isn't accounted for in the regex being used.
It is looking for `Scarcity - (2|4|6|8|10)x Merchant Item Rarity\.esp`.

**Comment by parsafaramarzi** [comment]
yup issue is fixed now set the other esps as optional esp and now issue is fixed

**Comment by parsafaramarzi** [comment]
although i still wish for this to be fixed so that loot can see if a plugin is hidden

**Comment by Ortham** [comment]
Is `.mohidden` equivalent to `.ghost`, i.e. a file extension that's appended to plugin filenames to stop the game from seeing the plugin without moving it out of the Data folder?

**Comment by CptMcSplody** [comment]
> Is `.mohidden` equivalent to `.ghost`, i.e. a file extension that's appended to plugin filenames to stop the game from seeing the plugin without moving it out of the Data folder?

Yeah same idea as `.ghost`.

**Comment by Ortham** [comment]
In that case @parsafaramarzi if you file another issue about supporting `.mohidden` plugins, I'm open to adding support for them.
