### ISSUE TITLE
Redate plugins with identical timestamps when no changes to load order are made

### ISSUE THREAD

**Issue by sibir-ine** [loot/loot#1484]
In games where timestamps determine load order (i.e. Oblivion, Fallout 3), if multiple plugins share the same timestamp but no changes to load order are made upon sort, they aren't redated. Considering this can cause issues & pertains to load order, I think it'd be appropriate for LOOT to rectify this regardless of whether it detects changes to load order.

**Comment by Ortham** [comment]
I see a few different problems with how LOOT handles writing unchanged load orders:

1. Inconsistent behaviour between games: as you've said, for some LOOT will write a load order if there aren't any changes, while for others it won't
2. Surprising behaviour: as a user, I wouldn't expect LOOT to be making any changes if I decide not to click the Apply button, and writing the load order is a change whether or not it looks like one to LOOT.
3. LOOT's interpretation of ambiguous load orders (e.g. plugins with equal timestamp, or plugins not listed in `plugins.txt`) may not match the game's or other utilities', so LOOT's write may actually have an effect on the game or other utilities.

Maybe the best approach is to always write the load order if LOOT thinks it's unchanged, but to also offer a toggle setting to disable that behaviour for anyone who finds it causes problems for them?

**Comment by sibir-ine** [comment]
I think that sounds reasonable.

**Comment by Ortham** [comment]
Looking at this again, I've changed my opinion slightly: rather than providing an option to opt out of silent load order writes, I think it would be better if LOOT warned users when it saw a load order that is ambiguous and provided an option to fix the ambiguity. That could be done when the game is initially loaded, so that it's independent from sorting.

I've mostly implemented the ambiguity checks in libloadorder (only Skyrim to go), and then it's a matter of plumbing it through libloot and into LOOT, and deciding how best to implement it in the UI.

**Comment by Ortham** [comment]
I've implemented this in the `check-ambiguity` branch. In it, LOOT now checks if the current load order is ambiguous after performing most operations that cause the load order state to be reloaded (that's loading game data or sorting). The exception is that if sorting results in changes the check is only done if you then discard the sorted load order, because if you apply the sorted load order that will also resolve the ambiguity.

If ambiguity is detected, LOOT displays a warning dialog box that says so, and tells the user they can fix it using a new Game menu action. That action is disabled until ambiguity is disabled, and disabled itself again after running. The action just saves the load order that's seen by LOOT. I decided to separate out the dialog from the action so that the user has a chance to scroll through the load order in LOOT before making any decision.

The new menu action also replaces the existing behaviour where LOOT would always apply an unchanged load order for Skyrim and newer games, because the new behaviour makes that redundant (unless the ambiguity check is bugged and misses some cases).

@sibir-ine Can you check the new functionality to see if it behaves as you want? The easiest ways to trigger ambiguity are to have two or more plugins with the same timestamp in a timestamp-based game, or remove some plugins from your Skyrim SE / Fallout 4 plugins.txt file.

**Comment by sibir-ine** [comment]
The action works well. However, I noticed three issues. First, if you try to sort an ambiguous load order that isn't resolved by sorting, the dialog is displayed twice in sequence.

> The exception is that if sorting results in changes the check is only done if you then discard the sorted load order, because if you apply the sorted load order that will also resolve the ambiguity.

Second, this doesn't appear to be the case. It still appears after sorting but before applying or discarding. The action is also still available in this period which seems like there's potential for issues (or at least confusion) with allowing people to resolve the ambiguity while there's still a sorted order to be applied or discarded.

Third, after applying resolves the ambiguity, the action is still available in the _Game_ menu until refreshing or sorting again.

**Comment by Ortham** [comment]
Those issues should now be fixed, try again?

**Comment by sibir-ine** [comment]
Yup, everything appears to be working as expected, & the new icons look good. Thanks 👍

**Comment by Ortham** [comment]
Great, I'm going to keep this open for a bit since it requires a new libloot release and I want to get through a few more issues before making one, in case there are other breaking changes needed.

**Comment by Ortham** [comment]
Merged in c6412a36297adbcc3d897c25dca79fdb2e589bd9.
