### ISSUE TITLE
LOOT Crashes on Opening "Edit Groups"

### ISSUE THREAD

**Issue by RacerBG** [loot/loot#1975]
Debug Log:
```
[21:20:51.477452] [info]: Running 64-bit LOOT on KDE Flatpak runtime and the x86_64 CPU architecture
[21:20:51.477520] [info]: LOOT version: 0.22.3+8578197d
[21:20:51.477543] [info]: libloot version: 0.22.3+b23e3314
[21:20:51.481244] [warning]: The file at $HOME/.var/app/io.github.loot.loot/data/Steam/config/libraryfolders.vdf could not be opened for reading
[21:20:51.623153] [warning]: Failed to find the style sheet for the "default" theme in the filesystem, attempting to load from built-in resources...
[21:20:51.797256] [info]: Initialising filesystem-related data for game: TES V: Skyrim Special Edition
[21:20:51.797405] [info]: Attempting to create a game handle for game type "The Elder Scrolls V: Skyrim Special Edition" with game path "$HOME/.local/share/games/steamapps/common/Skyrim Special Edition" and game local path "$HOME/.local/share/games/steamapps/compatdata/489830/pfx/drive_c/users/steamuser/AppData/Local/Skyrim Special Edition"
```

Terminal Output:
```
Qt: Session management error: Could not open network socket
QIODevice::read (QFile, "~/.var/app/io.github.loot.loot/config/heroic/gog_store/installed.json"): device not open
QIODevice::read (QFile, "~/.var/app/io.github.loot.loot/config/heroic/legendaryConfig/legendary/installed.json"): device not open
QIODevice::read (QFile, "~/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/installed.json"): device not open
QIODevice::read (QFile, "~/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary/installed.json"): device not open
QLayout::addChildLayout: layout QFormLayout "" already has a parent
```

**Comment by Ortham** [comment]
Does it still crash if you use the latest master branch build's flatpak [here](https://github.com/loot/loot/actions/runs/9036110645)?

**Comment by RacerBG** [comment]
Yes.

```
Qt: Session management error: Could not open network socket
QIODevice::read (QFile, "~/.var/app/io.github.loot.loot/config/heroic/gog_store/installed.json"): device not open
QIODevice::read (QFile, "~/.var/app/io.github.loot.loot/config/heroic/legendaryConfig/legendary/installed.json"): device not open
QIODevice::read (QFile, "~/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/installed.json"): device not open
QIODevice::read (QFile, "~/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary/installed.json"): device not open
QLayout::addChildLayout: layout QFormLayout "" already has a parent
```

```
[22:31:47.267041] [info]: Running 64-bit LOOT on KDE Flatpak runtime and the x86_64 CPU architecture
[22:31:47.267113] [info]: LOOT version: 0.22.3+e9101c60
[22:31:47.267122] [info]: libloot version: 0.22.4+
[22:31:47.267534] [warning]: The file at $HOME/.var/app/io.github.loot.loot/data/Steam/config/libraryfolders.vdf could not be opened for reading
[22:31:47.405428] [warning]: Failed to find the style sheet for the "default" theme in the filesystem, attempting to load from built-in resources...
[22:31:47.568568] [info]: Backup of $HOME/.var/app/io.github.loot.loot/data/LOOT created in $HOME/.var/app/io.github.loot.loot/data/LOOT/backups/LOOT-backup-20240510T223147
[22:31:50.305485] [info]: Initialising filesystem-related data for game: Fallout 3
[22:31:50.305524] [info]: Attempting to create a game handle for game type "Fallout 3" with game path "$HOME/.local/share/games/steamapps/common/Fallout 3 goty" and game local path "$HOME/.local/share/games/steamapps/compatdata/22370/pfx/drive_c/users/steamuser/AppData/Local/Fallout3"
[22:31:50.334618] [warning]: No masterlist prelude present at $HOME/.var/app/io.github.loot.loot/data/LOOT/prelude/prelude.yaml
[22:31:50.334687] [warning]: No masterlist present at $HOME/.var/app/io.github.loot.loot/data/LOOT/games/Fallout3/masterlist.yaml
[22:31:50.720922] [info]: No LOOT update is available.
[22:31:54.724929] [info]: Initialising filesystem-related data for game: TES V: Skyrim Special Edition
[22:31:54.725026] [info]: Attempting to create a game handle for game type "The Elder Scrolls V: Skyrim Special Edition" with game path "$HOME/.local/share/games/steamapps/common/Skyrim Special Edition" and game local path "$HOME/.local/share/games/steamapps/compatdata/489830/pfx/drive_c/users/steamuser/AppData/Local/Skyrim Special Edition"
[22:31:54.799278] [warning]: No cached card exists for row 0, card sizes may not be calculated correctly
[22:31:54.808939] [warning]: No masterlist prelude present at $HOME/.var/app/io.github.loot.loot/data/LOOT/prelude/prelude.yaml
[22:31:54.809026] [warning]: No masterlist present at $HOME/.var/app/io.github.loot.loot/data/LOOT/games/Skyrim Special Edition/masterlist.yaml
[22:31:57.962268] [info]: Writing file revision info for $HOME/.var/app/io.github.loot.loot/data/LOOT/prelude/prelude.yaml.metadata.toml with ID e5ff40be50ba4d18d1293758ec3d683b1cbe2a5c and date 2024-05-10
[22:31:58.303786] [info]: Writing file revision info for $HOME/.var/app/io.github.loot.loot/data/LOOT/games/Skyrim Special Edition/masterlist.yaml.metadata.toml with ID cc356285538d9d22fb19c167dcad021a5f8aadd0 and date 2024-05-10
[22:31:59.381877] [warning]: No cached card exists for row 0, card sizes may not be calculated correctly
[22:31:59.397370] [warning]: No cached card exists for row 2, card sizes may not be calculated correctly
[22:31:59.403718] [warning]: No cached card exists for row 3, card sizes may not be calculated correctly
[22:31:59.408741] [warning]: No cached card exists for row 4, card sizes may not be calculated correctly
[22:31:59.413520] [warning]: No cached card exists for row 5, card sizes may not be calculated correctly
```

**Comment by Ortham** [comment]
I'm not able to see a crash when running LOOT for Morrowind in a VM. Can you enable debug logging in LOOT's settings, quit and relaunch LOOT, then try to open the groups editor again and upload the log that produces?

**Comment by RacerBG** [comment]
[LOOTDebugLog.txt](https://github.com/loot/loot/files/15280029/LOOTDebugLog.txt)

**Comment by Ortham** [comment]
Thanks, it seems that it's crashing during layout calculation, or maybe it's a rendering issue. Can you try again with [this build](https://github.com/loot/loot/actions/runs/9038328733)?

**Comment by RacerBG** [comment]
[LOOTDebugLog.txt](https://github.com/loot/loot/files/15282985/LOOTDebugLog.txt)

**Comment by Ortham** [comment]
That didn't help... Can you try [this build](https://github.com/loot/loot/actions/runs/9045236254)?

**Comment by RacerBG** [comment]
[LOOTDebugLog.txt](https://github.com/loot/loot/files/15283688/LOOTDebugLog.txt)

**Comment by Ortham** [comment]
Something weird is going on... Can you try [this build](https://github.com/loot/loot/actions/runs/9045516487)?

**Comment by RacerBG** [comment]
[LOOTDebugLog.txt](https://github.com/loot/loot/files/15283963/LOOTDebugLog.txt)

**Comment by Ortham** [comment]
It's crashing at the bit I wasn't expecting to matter... I've disabled some unnecessary config in case that was the issue, can you try [this build](https://github.com/loot/loot/actions/runs/9045791470)?

**Comment by RacerBG** [comment]
[LOOTDebugLog.txt](https://github.com/loot/loot/files/15284092/LOOTDebugLog.txt)

**Comment by Ortham** [comment]
@RacerBG I've published a build with some debug info through Flathub, can you install it like so:

```
flatpak install --user https://dl.flathub.org/build-repo/104771/io.github.loot.loot.flatpakref
flatpak install --user loot-origin io.github.loot.loot.Debug
```

`loot-origin` should be whatever is displayed as the remote when the first command runs: it might be called something different for you.

You may need to uninstall other versions of LOOT to prevent confusion.

Once installed, try running it again, and see if anything more is logged to the terminal when it crashes. If not, I think we'll have to get `gdb` involved.

**Comment by RacerBG** [comment]
[LOOTDebugLog.txt](https://github.com/loot/loot/files/15366786/LOOTDebugLog.txt)

It still crashes. On the positive side though LOOT looks well integrated with KDE thanks to the update to Runtime 6.7. 

There is a small styling issue though, the position of the "Plugins" and "Filters" tabs is centered right now while it should be on the left as it was before?

**Comment by Ortham** [comment]
> It still crashes.

And there was nothing new in your terminal?

Can you try the following in a terminal?

1. Run `flatpak run --command=sh --devel io.github.loot.loot`
2. In the shell started by the previous command, run `gdb /usr/bin/LOOT`
3. In gdb enter `run`
4. It'll ask if you want to enable debuginfod for this session, choose `n`
5. It'll start up LOOT, now replicate the crash by opening the groups editor.
6. Back in gdb enter `bt` to show the backtrace
7. Copy/paste the terminal contents since step 1 into this issue (in a code block so it doesn't get misformatted)

> There is a small styling issue though, the position of the "Plugins" and "Filters" tabs is centered right now while it should be on the left as it was before? And their horizontal size is suboptimal. The text string is not entirely visible.

Yes, I only noticed this when testing the release build, I'll have to investigate what I can do about the changes.

**Comment by RacerBG** [comment]
> And there was nothing new in your terminal?

Still the same.

> Run flatpak run --command=sh --devel io.github.loot.loot
> In the shell started by the previous command, run gdb /usr/bin/LOOT

I had to install SDK 6.7 in order to do that but after entering `gdb /usr/bin/LOOT` it says `/usr/bin/LOOT: No such file or directory.`

**Comment by Ortham** [comment]
Sorry, it's `/app/bin/LOOT`, not `/usr/bin/LOOT`.

**Comment by RacerBG** [comment]
`Starting program: /app/bin/LOOT
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff1d696c0 (LWP 16)]
[New Thread 0x7ffff15686c0 (LWP 17)]
[New Thread 0x7fffdebff6c0 (LWP 18)]
[New Thread 0x7fffde3fe6c0 (LWP 19)]
[New Thread 0x7fffddbfd6c0 (LWP 20)]
[New Thread 0x7fffdd3fc6c0 (LWP 21)]
[New Thread 0x7fffcffff6c0 (LWP 22)]
[New Thread 0x7fffcf7fe6c0 (LWP 23)]
[New Thread 0x7fffceffd6c0 (LWP 24)]
[New Thread 0x7fffce7fc6c0 (LWP 25)]
[New Thread 0x7fffcdffb6c0 (LWP 26)]
[Thread 0x7fffcdffb6c0 (LWP 26) exited]
[Thread 0x7fffce7fc6c0 (LWP 25) exited]
[Thread 0x7fffceffd6c0 (LWP 24) exited]
Qt: Session management error: Could not open network socket
QIODevice::read (QFile, "/home/georgi/.var/app/io.github.loot.loot/config/heroic/gog_store/installed.json"): device not open
QIODevice::read (QFile, "/home/georgi/.var/app/io.github.loot.loot/config/heroic/legendaryConfig/legendary/installed.json"): device not open
QIODevice::read (QFile, "/home/georgi/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/installed.json"): device not open
QIODevice::read (QFile, "/home/georgi/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary/installed.json"): device not open
QLayout::addChildLayout: layout QFormLayout "" already has a parent
[New Thread 0x7fffceffd6c0 (LWP 27)]
[New Thread 0x7fffce7fc6c0 (LWP 28)]
[New Thread 0x7fffcdffb6c0 (LWP 29)]
[New Thread 0x7fffcd1ff6c0 (LWP 30)]
[New Thread 0x7fffb3fff6c0 (LWP 31)]
[New Thread 0x7fffb37fe6c0 (LWP 32)]
[New Thread 0x7fffb2ffd6c0 (LWP 33)]
[New Thread 0x7fffb27fc6c0 (LWP 34)]
[Thread 0x7fffb27fc6c0 (LWP 34) exited]
[New Thread 0x7fffcc2966c0 (LWP 35)]
[New Thread 0x7fffb1ffb6c0 (LWP 36)]
[New Thread 0x7fffb1dfa6c0 (LWP 37)]
[New Thread 0x7fffb1bf96c0 (LWP 38)]
[New Thread 0x7fffb19f86c0 (LWP 39)]
[New Thread 0x7fffb17f76c0 (LWP 40)]
[New Thread 0x7fffb15f66c0 (LWP 41)]
[New Thread 0x7fffb13f56c0 (LWP 42)]
[New Thread 0x7fffb0ada6c0 (LWP 43)]
[New Thread 0x7fffb06d96c0 (LWP 44)]
[New Thread 0x7fff7ffff6c0 (LWP 45)]
[New Thread 0x7fff7f3fc6c0 (LWP 46)]
[New Thread 0x7fff7fbfe6c0 (LWP 47)]
[New Thread 0x7fff7f7fd6c0 (LWP 48)]
[New Thread 0x7fff7effb6c0 (LWP 49)]
[Thread 0x7fff7effb6c0 (LWP 49) exited]
[Thread 0x7fff7f7fd6c0 (LWP 48) exited]
[Thread 0x7fff7fbfe6c0 (LWP 47) exited]
[Thread 0x7fff7f3fc6c0 (LWP 46) exited]
[Thread 0x7fff7ffff6c0 (LWP 45) exited]
[Thread 0x7fffb06d96c0 (LWP 44) exited]
[Thread 0x7fffb0ada6c0 (LWP 43) exited]
[Thread 0x7fffb37fe6c0 (LWP 32) exited]
[Thread 0x7fffb2ffd6c0 (LWP 33) exited]
[New Thread 0x7fffb0ada6c0 (LWP 50)]
[New Thread 0x7fff7f3fc6c0 (LWP 51)]
[New Thread 0x7fff7ffff6c0 (LWP 52)]
[New Thread 0x7fffb37fe6c0 (LWP 54)]
[New Thread 0x7fffb27fc6c0 (LWP 55)]
[New Thread 0x7fffb2ffd6c0 (LWP 53)]
[New Thread 0x7fffb06d96c0 (LWP 56)]
[Thread 0x7fffb06d96c0 (LWP 56) exited]
[Thread 0x7fffb27fc6c0 (LWP 55) exited]
[Thread 0x7fffb37fe6c0 (LWP 54) exited]
[Thread 0x7fffb2ffd6c0 (LWP 53) exited]
[Thread 0x7fff7ffff6c0 (LWP 52) exited]
[Thread 0x7fff7f3fc6c0 (LWP 51) exited]
[Thread 0x7fffb0ada6c0 (LWP 50) exited]
[Thread 0x7fffb3fff6c0 (LWP 31) exited]

Thread 1 "LOOT" received signal SIGILL, Illegal instruction.
0x00005555559052fd in ?? ()
(gdb) bt
#0  0x00005555559052fd in ?? ()
#1  0x0000555555905dee in ?? ()
#2  0x00005555556d1d40 in ?? ()
#3  0x00005555556cac86 in ?? ()
#4  0x00005555556cb7ca in ?? ()
#5  0x00005555556c2538 in ?? ()
#6  0x00005555557139e6 in ?? ()
#7  0x000055555564daf4 in ?? ()
#8  0x00007ffff59e6ea5 in ?? () from /usr/lib/x86_64-linux-gnu/libQt6Core.so.6
#9  0x00007ffff660aa34 in QAction::triggered(bool) () from /usr/lib/x86_64-linux-gnu/libQt6Gui.so.6
#10 0x00007ffff660d9eb in QAction::activate(QAction::ActionEvent) () from /usr/lib/x86_64-linux-gnu/libQt6Gui.so.6
#11 0x00007ffff6d7c714 in ?? () from /usr/lib/x86_64-linux-gnu/libQt6Widgets.so.6
#12 0x00007ffff6d84a80 in ?? () from /usr/lib/x86_64-linux-gnu/libQt6Widgets.so.6
#13 0x00007ffff6bfd0e8 in QWidget::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt6Widgets.so.6
#14 0x00007ffff6b9e258 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt6Widgets.so.6
#15 0x00007ffff6ba7dca in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt6Widgets.so.6
#16 0x00007ffff5984700 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt6Core.so.6
#17 0x00007ffff6ba65b3 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) ()
from /usr/lib/x86_64-linux-gnu/libQt6Widgets.so.6
#18 0x00007ffff6c10d50 in ?? () from /usr/lib/x86_64-linux-gnu/libQt6Widgets.so.6
#19 0x00007ffff6c131b0 in ?? () from /usr/lib/x86_64-linux-gnu/libQt6Widgets.so.6
#20 0x00007ffff6b9e258 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt6Widgets.so.6
#21 0x00007ffff5984700 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt6Core.so.6
#22 0x00007ffff61e556f in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) ()
from /usr/lib/x86_64-linux-gnu/libQt6Gui.so.6
#23 0x00007ffff624688c in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
from /usr/lib/x86_64-linux-gnu/libQt6Gui.so.6
#24 0x00007ffff20f3a76 in ?? () from /usr/lib/x86_64-linux-gnu/libQt6XcbQpa.so.6
#25 0x00007ffff5317e59 in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#26 0x00007ffff53752b8 in g_main_context_iterate.isra () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#27 0x00007ffff5315513 in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#28 0x00007ffff5c7451f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt6Core.so.6
#29 0x00007ffff599120b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt6Core.so.6
#30 0x00007ffff598d44d in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQt6Core.so.6
--Type <RET> for more, q to quit, c to continue without paging--
#31 0x0000555555642167 in ?? ()
#32 0x00007ffff4e3b08a in __libc_start_call_main () from /usr/lib/x86_64-linux-gnu/libc.so.6
#33 0x00007ffff4e3b14b in __libc_start_main () from /usr/lib/x86_64-linux-gnu/libc.so.6
#34 0x0000555555644a55 in ?? ()`

**Comment by Ortham** [comment]
It looks like that didn't load any of LOOT's debug symbols...

**Comment by RacerBG** [comment]
> It looks like that didn't load any of LOOT's debug symbols...

They were enabled though.

**Comment by Ortham** [comment]
Yeah, I'm not sure what's going on.

**Comment by RacerBG** [comment]
> @RacerBG Do you use any groups that you've set up yourself? If yes, does the editor still crash, if you temporarily remove your `userlist.yaml`? Also, does the crash happens only for one specific game, or for every game that you've got installed?

No I do not have any self made groups, I do not even use that feature. I have reported it because I saw that it wasn't working and the crash happens for every game basically.

**Comment by pStyl3** [comment]
Does the crash also occur with the Flatpak version of LOOT `v0.22.3`?

**Comment by RacerBG** [comment]
> Does the crash also occur with the Flatpak version of LOOT `v0.22.3`?

Yes.

**Comment by pStyl3** [comment]
If you still have them, please also test `v0.22.2`, `v0.22.1`, `v0.22.0` and `v0.21.0` in descending order, until you find a version where the crash doesn't happen.

**Comment by RacerBG** [comment]
First, I would like to see a few confirmations of this bug from another users as well if possible. If I'm an isolated case, then it's quite worthless to pursue a solution. As I said - I'm not interested in this feature.

**Comment by pStyl3** [comment]
That might be the case, but a crash is still a bug that shouldn't happen. Apparently it's an issue where the source of the problem isn't quite so easy to figure out. So - let's try to find out in which version the bug was introduced! If we can pinpoint that, so if we are able to say in version X-45 the groups editor works, but in X-46 it starts to crash, then Ortham can take that information to narrow the cause down. We've done similar bug hunts in the past, and that's why I suggested to try out a few older versions of LOOT.

**Comment by RacerBG** [comment]
> That might be the case, but a crash is still a bug that shouldn't happen. Apparently it's an issue where the source of the problem isn't quite so easy to figure out. So - let's try to find out in which version the bug was introduced! If we can pinpoint that, so if we are able to say in version X-45 the groups editor works, but in X-46 it starts to crash, then Ortham can take that information to narrow the cause down. We've done similar bug hunts in the past, and that's why I suggested to try out a few older versions of LOOT.

Looks like the first Flatpak version is 0.21.0. Let's do this (for science)!

**Comment by pStyl3** [comment]
> EDIT: The earliest to which I was able to downgrade is LOOT 0.22.0:
> 
> Commit: 0773c95394e6e6cd54728871a27545a4999c45b39cb55ab005fd213c150dad17
> Subject: Update to v0.22.0 release (41c1112f)
> Date: 2023-10-07 21:47:41 +0000

And that version also crashes?

**Comment by RacerBG** [comment]
> > EDIT: The earliest to which I was able to downgrade is LOOT 0.22.0:
> > Commit: 0773c95394e6e6cd54728871a27545a4999c45b39cb55ab005fd213c150dad17
> > Subject: Update to v0.22.0 release (41c1112f)
> > Date: 2023-10-07 21:47:41 +0000
> 
> And that version also crashes?

In exactly the same way, here is the log file:

[LOOTDebugLog.txt](https://github.com/loot/loot/files/15444479/LOOTDebugLog.txt)

**Comment by Thijxx** [comment]
I get the same result from LOOT when I start it using the terminal the following way, a regular start without parameters works fine.

`flatpak run io.github.loot.loot --game-path="/mnt/steam/SteamLibrary/steamapps/common/Skyrim Special Edition/" --game="Skyrim Special Edition" --auto-sort`

The debug log talks about Oblivion and I do not know why. It is impossible to delete from LOOT, after delete I re-open the settings and it is there again.

```
Qt: Session management error: Could not open network socket
QIODevice::read (QFile, "/home/thijs/.var/app/io.github.loot.loot/config/heroic/legendaryConfig/legendary/installed.json"): device not open
QIODevice::read (QFile, "/home/thijs/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/installed.json"): device not open
QIODevice::read (QFile, "/home/thijs/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary/installed.json"): device not open
QLayout::addChildLayout: layout QFormLayout "" already has a parent
```

debug log
```
[21:07:55.240987] [info]: Running 64-bit LOOT on KDE Flatpak runtime and the x86_64 CPU architecture
[21:07:55.241023] [info]: LOOT version: 0.23.0+f1329f7
[21:07:55.241031] [info]: libloot version: 0.23.0+f3eabb6
[21:07:55.241471] [debug]: Failed to get preferred UI language from locale: std::bad_cast
[21:07:55.241482] [debug]: Preferred UI languages are: en_US.UTF-8
[21:07:55.241699] [debug]: Detecting installed games.
[21:07:55.241719] [trace]: Reading libraryfolders.vdf file at $HOME/.var/app/io.github.loot.loot/data/Steam/config/libraryfolders.vdf
[21:07:55.241893] [trace]: Reading libraryfolders.vdf file at $HOME/.var/app/com.valvesoftware.Steam/.local/share/Steam/config/libraryfolders.vdf
[21:07:55.241905] [warning]: The file at $HOME/.var/app/com.valvesoftware.Steam/.local/share/Steam/config/libraryfolders.vdf could not be opened for reading
[21:07:55.241911] [trace]: Reading Heroic installed GOG games file at $HOME/.var/app/io.github.loot.loot/config/heroic/gog_store/installed.json.
[21:07:55.241951] [trace]: Skipping app name 1207658879 as it is not a supported game
[21:07:55.241956] [trace]: Skipping app name 1207659163 as it is not a supported game
[21:07:55.241962] [trace]: Reading Heroic installed EGS games file at $HOME/.var/app/io.github.loot.loot/config/heroic/legendaryConfig/legendary/installed.json.
[21:07:55.241984] [trace]: Reading Heroic installed GOG games file at $HOME/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/installed.json.
[21:07:55.242002] [trace]: Reading Heroic installed EGS games file at $HOME/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary/installed.json.
[21:07:55.242015] [trace]: Checking if game "TES III: Morrowind" is installed.
[21:07:55.242024] [trace]: Checking if game "TES IV: Oblivion" is installed.
[21:07:55.242029] [trace]: Checking if game "Nehrim - At Fate's Edge" is installed.
[21:07:55.242033] [trace]: Checking if game "TES V: Skyrim" is installed.
[21:07:55.242037] [trace]: Checking if game "Enderal: Forgotten Stories" is installed.
[21:07:55.242041] [trace]: Checking if game "TES V: Skyrim Special Edition" is installed.
[21:07:55.242046] [trace]: Checking if game "Enderal: Forgotten Stories (Special Edition)" is installed.
[21:07:55.242050] [trace]: Checking if game "TES V: Skyrim VR" is installed.
[21:07:55.242054] [trace]: Checking if game "Fallout 3" is installed.
[21:07:55.242059] [trace]: Checking if game "Fallout: New Vegas" is installed.
[21:07:55.242063] [trace]: Checking if game "Fallout 4" is installed.
[21:07:55.242068] [trace]: Checking if game "Fallout 4 VR" is installed.
[21:07:55.242072] [trace]: Checking if game "Starfield" is installed.
[21:07:55.242112] [trace]: Checking if game "TES IV: Oblivion" is installed.
[21:07:55.242120] [trace]: Adding new installed game entry for: Oblivion
[21:07:55.242128] [trace]: Checking if game "sky" is installed.
[21:07:55.242137] [trace]: Adding new installed game entry for: hello
[21:07:55.242147] [debug]: Setting the current game to that with folder: Oblivion
[21:07:55.242151] [debug]: New game is: TES IV: Oblivion
[21:07:55.242154] [debug]: Game selected is TES IV: Oblivion
[21:07:55.288023] [debug]: Loading style sheet for the "default" theme...
[21:07:55.288055] [warning]: Failed to find the style sheet for the "default" theme in the filesystem, attempting to load from built-in resources...
[21:07:55.288069] [debug]: Current style name is breeze
[21:07:55.288073] [debug]: Loading default-dark theme instead of the default theme as a dark colour scheme has been detected
[21:07:55.288077] [debug]: Loading style sheet for the "default-dark" theme...
[21:07:55.288084] [warning]: Failed to find the style sheet for the "default-dark" theme in the filesystem, attempting to load from built-in resources...
[21:07:55.346934] [info]: Initialising filesystem-related data for game: TES IV: Oblivion
[21:07:55.346998] [info]: Attempting to create a game handle for game type "The Elder Scrolls IV: Oblivion" with game path "/mnt/steam/SteamLibrary/steamapps/common/Oblivion" and game local path "/mnt/steam/SteamLibrary/steamapps/compatdata/22330/pfx/drive_c/users/steamuser/AppData/Local/Oblivion"
[21:07:55.348526] [debug]: Game named TES IV: Oblivion has been initialised
```

**Comment by Ortham** [comment]
> I get the same result from LOOT when I start it using the terminal the following way, a regular start without parameters works fine.

Can you also share your LOOT's `settings.toml` file?

**Comment by Ortham** [comment]
> I get the same result from LOOT when I start it using the terminal the following way, a regular start without parameters works fine.
> 
> `flatpak run io.github.loot.loot --game-path="/mnt/steam/SteamLibrary/steamapps/common/Skyrim Special Edition/" --game="Skyrim Special Edition" --auto-sort`
> 
> The debug log talks about Oblivion and I do not know why. It is impossible to delete from LOOT, after delete I re-open the settings and it is there again.

You've got an entry for Skyrim in your settings that uses the folder name `hello`, so you don't need to pass `--game-path` and `--game="Skyrim Special Edition"` should be `--game=hello`. Do you still get the crash with those changes?

LOOT is defaulting to Oblivion because it can't find an entry for `Skyrim Special Edition` (because you've named it `hello`) so it falls back to the first game that it detected, which is Oblivion.

**Comment by Thijxx** [comment]
I was hoping to use LOOT from the command line without ever opening the GUI so I can call it from another application and do an auto-sort. So in this case there is no 'hello' and I'd like it to recognize the game.

Using the 'hello' game name works so that's nice, I did not know it was that label that I set manually. I can see it in the docs so I could/should have known this; https://loot.readthedocs.io/en/stable/app/usage/initialisation.html

For completeness' sake, this is the response when I use 'hello' and everything works fine.

**Command** `flatpak run io.github.loot.loot --game="hello" --auto-sort`

**Response**
```
Qt: Session management error: Could not open network socket
QIODevice::read (QFile, "/home/thijs/.var/app/io.github.loot.loot/config/heroic/legendaryConfig/legendary/installed.json"): device not open
QIODevice::read (QFile, "/home/thijs/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/installed.json"): device not open
QIODevice::read (QFile, "/home/thijs/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary/installed.json"): device not open
QLayout::addChildLayout: layout QFormLayout "" already has a parent
```

**Comment by Ortham** [comment]
> I was hoping to use LOOT from the command line without ever opening the GUI so I can call it from another application and do an auto-sort. So in this case there is no 'hello' and I'd like it to recognize the game.

It should work as you expect if you remove the game entry for Skyrim SE from your `settings.toml` - LOOT should then autodetect it as `Skyrim Special Edition` (so you can pass that to `--game`), since there'll be no existing configuration for the same game install. The way the autodetection works with the config is that LOOT will try to detect installed games and then merge what it's found with what it's got configured in its settings, so you don't end up with duplicate entries for the same game.

**Comment by RacerBG** [comment]
Test results with LOOT 0.26.0:

Running it through a terminal it gives the following output:

```
QIODevice::read (QFile, "/home/georgi/.var/app/io.github.loot.loot/config/heroic/gog_store/installed.json"): device not open
QIODevice::read (QFile, "/home/georgi/.var/app/io.github.loot.loot/config/heroic/legendaryConfig/legendary/installed.json"): device not open
QIODevice::read (QFile, "/home/georgi/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary/installed.json"): device not open
QLayout::addChildLayout: layout QFormLayout "" already has a parent
```

Here is the log file:
[LOOTDebugLog.txt](https://github.com/user-attachments/files/20024332/LOOTDebugLog.txt)

The end result is still the same. My Flatpak version is currently 1.16.0.

**Comment by RacerBG** [comment]
> [@RacerBG](https://github.com/RacerBG) Can you try [this build](https://github.com/loot/loot/actions/runs/14841217803)?

Sorry for the delay, here are the results:
[LOOTDebugLog.txt](https://github.com/user-attachments/files/20104511/LOOTDebugLog.txt)

The terminal output is still the same and it is not related to the crash or so it seems.

**Comment by Ortham** [comment]
> TLDR, it crashes right after the following lines:
> 
> `[17:27:18.771692] [trace]: Checking if the load order is ambiguous. [17:27:21.738551] [debug]: Calculating new graph layout [17:27:21.738621] [trace]: Called calculateGraphLayout() [17:27:21.738645] [trace]: Creating graph attributes`

Thanks, that means it's crashing in third-party code that should just be doing some basic initialisation, I'll have to dig into it to see if I can spot anything.

**Comment by RacerBG** [comment]
It didn't ask me to enable debug info but the output is here:

`Starting program: /app/bin/LOOT
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/x86_64-linux-gnu/libthread_db.so.1".
Detected locale "C" with character encoding "ANSI_X3.4-1968", which is not UTF-8.
Qt depends on a UTF-8 locale, and has switched to "C.UTF-8" instead.
If this causes problems, reconfigure your locale. See the locale(1) manual
for more information.
[New Thread 0x7ffff1e8f6c0 (LWP 16)]
[New Thread 0x7fffea3f56c0 (LWP 17)]
[New Thread 0x7fffe9bf46c0 (LWP 18)]
[New Thread 0x7fffe92b36c0 (LWP 19)]
[New Thread 0x7fffe893c6c0 (LWP 20)]
[New Thread 0x7fffe15ff6c0 (LWP 21)]
[New Thread 0x7fffe0dfe6c0 (LWP 22)]
[New Thread 0x7fffd63ff6c0 (LWP 23)]
[New Thread 0x7fffd5bfe6c0 (LWP 24)]
[New Thread 0x7fffd53fd6c0 (LWP 25)]
[New Thread 0x7fffd4bfc6c0 (LWP 26)]
[New Thread 0x7fffaffff6c0 (LWP 27)]
[New Thread 0x7fffaf7fe6c0 (LWP 28)]
[New Thread 0x7fffaeffd6c0 (LWP 29)]
[New Thread 0x7fffae7fc6c0 (LWP 30)]
[New Thread 0x7fffadffb6c0 (LWP 31)]
[Thread 0x7fffadffb6c0 (LWP 31) exited]
[Thread 0x7fffae7fc6c0 (LWP 30) exited]
[Thread 0x7fffaeffd6c0 (LWP 29) exited]
[Thread 0x7fffaf7fe6c0 (LWP 28) exited]
[Thread 0x7fffaffff6c0 (LWP 27) exited]
[Thread 0x7fffd4bfc6c0 (LWP 26) exited]
QIODevice::read (QFile, "/home/georgi/.var/app/io.github.loot.loot/config/heroic/gog_store/installed.json"): device not open
QIODevice::read (QFile, "/home/georgi/.var/app/io.github.loot.loot/config/heroic/legendaryConfig/legendary/installed.json"): device not open
QIODevice::read (QFile, "/home/georgi/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary/installed.json"): device not open
QLayout::addChildLayout: layout QFormLayout "" already has a parent
[New Thread 0x7fffd4bfc6c0 (LWP 32)]
[New Thread 0x7fffaffff6c0 (LWP 33)]
[New Thread 0x7fffaf7fe6c0 (LWP 34)]
[New Thread 0x7fffaeffd6c0 (LWP 35)]
[New Thread 0x7fffad3fe6c0 (LWP 37)]
[New Thread 0x7fffadbff6c0 (LWP 36)]
[New Thread 0x7fffad1fd6c0 (LWP 38)]
[Thread 0x7fffadbff6c0 (LWP 36) exited]
[New Thread 0x7fffacffc6c0 (LWP 39)]
[New Thread 0x7fffac7fb6c0 (LWP 40)]
[Thread 0x7fffacffc6c0 (LWP 39) exited]
[New Thread 0x7fffac5fa6c0 (LWP 41)]
[New Thread 0x7fffac3f96c0 (LWP 42)]
[New Thread 0x7fff8ffff6c0 (LWP 43)]
[New Thread 0x7fff87fff6c0 (LWP 44)]
[New Thread 0x7fff8fdfe6c0 (LWP 45)]
[New Thread 0x7fff8f9fb6c0 (LWP 46)]
[New Thread 0x7fff8f5fa6c0 (LWP 48)]
[New Thread 0x7fff8f1f96c0 (LWP 47)]
[New Thread 0x7fff8edf86c0 (LWP 49)]
[New Thread 0x7fff8e9f76c0 (LWP 50)]
[New Thread 0x7fff8e5f66c0 (LWP 51)]
[New Thread 0x7fff8e1f56c0 (LWP 52)]
[Thread 0x7fffaeffd6c0 (LWP 35) exited]
[New Thread 0x7fffacffc6c0 (LWP 53)]
[New Thread 0x7fffadbff6c0 (LWP 54)]
[New Thread 0x7fffaeffd6c0 (LWP 55)]
[Thread 0x7fffacffc6c0 (LWP 53) exited]
[Thread 0x7fff8e1f56c0 (LWP 52) exited]
[Thread 0x7fff8e5f66c0 (LWP 51) exited]
[Thread 0x7fff8e9f76c0 (LWP 50) exited]
[Thread 0x7fff8edf86c0 (LWP 49) exited]
[Thread 0x7fff8f5fa6c0 (LWP 48) exited]
[Thread 0x7fff8f1f96c0 (LWP 47) exited]
[Thread 0x7fff8f9fb6c0 (LWP 46) exited]
[Thread 0x7fffaf7fe6c0 (LWP 34) exited]
[Thread 0x7fffadbff6c0 (LWP 54) exited]

Thread 1 "LOOT" received signal SIGILL, Illegal instruction.
0x00005555558ddca2 in ?? ()
(gdb) bt
#0  0x00005555558ddca2 in ?? ()
#1  0x00005555558dde05 in ?? ()
#2  0x00005555558dd82e in ?? ()
#3  0x000055555590cbad in ?? ()
#4  0x000055555590dc65 in ?? ()
#5  0x000055555590f6e7 in ?? ()
#6  0x0000555555910a1b in ?? ()
#7  0x000055555569e17f in ?? ()
#8  0x0000555555699af1 in ?? ()
#9  0x000055555569a49f in ?? ()
#10 0x00005555556941f8 in ?? ()
#11 0x00005555556d96e1 in ?? ()
#12 0x000055555564d91f in ?? ()
#13 0x00007ffff560e20a in doActivate<false> (sender=0x55555615d810, signal_index=7, argv=0x7fffffffbbb0)
at /run/build-runtime/qt6-qtbase/src/corelib/kernel/qobject.cpp:4164
#14 0x00007ffff5604387 in QMetaObject::activate (sender=sender@entry=0x55555615d810, m=m@entry=0x7ffff65d6f60 <QAction::staticMetaObject>,
local_signal_index=local_signal_index@entry=4, argv=argv@entry=0x7fffffffbbb0) at /run/build-runtime/qt6-qtbase/src/corelib/kernel/qobject.cpp:4198
#15 0x00007ffff62a5fb4 in QMetaObject::activate<void, bool> (sender=0x55555615d810, mo=0x7ffff65d6f60 <QAction::staticMetaObject>, local_signal_index=4,
ret=0x0) at /run/build-runtime/qt6-qtbase/src/corelib/kernel/qobjectdefs.h:306
#16 QAction::triggered (this=this@entry=0x55555615d810, _t1=<optimized out>)
at /run/build-runtime/qt6-qtbase/src/gui/Gui_autogen/include/moc_qaction.cpp:372
#17 0x00007ffff62a91af in QAction::activate (this=0x55555615d810, event=<optimized out>) at /run/build-runtime/qt6-qtbase/src/gui/kernel/qaction.cpp:1104
#18 0x00007ffff79a2994 in QMenuPrivate::activateCausedStack (this=0x5555560fc790, causedStack=..., action=0x55555615d810, action_e=QAction::Trigger,
self=<optimized out>) at /run/build-runtime/qt6-qtbase/src/widgets/widgets/qmenu.cpp:1410
#19 0x00007ffff79ab950 in QMenuPrivate::activateAction (this=0x5555560fc790, action=0x55555615d810, action_e=QAction::Trigger, self=<optimized out>)
at /run/build-runtime/qt6-qtbase/src/widgets/widgets/qmenu.cpp:1492
#20 0x00007ffff7809a08 in QWidget::event (this=0x5555560fb800, event=0x7fffffffc270) at /run/build-runtime/qt6-qtbase/src/widgets/kernel/qwidget.cpp:9354
#21 0x00007ffff77a167d in QApplicationPrivate::notify_helper (this=this@entry=0x555555cd7290, receiver=receiver@entry=0x5555560fb800,
e=e@entry=0x7fffffffc270) at /run/build-runtime/qt6-qtbase/src/widgets/kernel/qapplication.cpp:3301
#22 0x00007ffff77ac09b in QApplication::notify (this=<optimized out>, receiver=<optimized out>, e=0x7fffffffc270)
at /run/build-runtime/qt6-qtbase/src/widgets/kernel/qapplication.cpp:2778
#23 0x00007ffff55a5808 in QCoreApplication::notifyInternal2 (receiver=0x5555560fb800, event=0x7fffffffc270)
at /run/build-runtime/qt6-qtbase/src/corelib/kernel/qcoreapplication.cpp:1106
#24 0x00007ffff55a5a7d in QCoreApplication::sendSpontaneousEvent (receiver=<optimized out>, event=<optimized out>)
--Type <RET> for more, q to quit, c to continue without paging--c
at /run/build-runtime/qt6-qtbase/src/corelib/kernel/qcoreapplication.cpp:1560
#25 0x00007ffff77aa64c in QApplicationPrivate::sendMouseEvent (receiver=0x5555560fb800, event=event@entry=0x7fffffffc270, alienWidget=<optimized out>,
nativeWidget=0x5555560fb800, buttonDown=buttonDown@entry=0x7ffff7de59f0 <qt_button_down>, lastMouseReceiver=..., spontaneous=true,
onlyDispatchEnterLeave=false) at /run/build-runtime/qt6-qtbase/src/widgets/kernel/qapplication.cpp:2359
#26 0x00007ffff781ebbb in QWidgetWindow::handleMouseEvent (this=0x555556f69930, event=event@entry=0x7fffffffc520)
at /run/build-runtime/qt6-qtbase/src/widgets/kernel/qwidgetwindow.cpp:577
#27 0x00007ffff78211c8 in QWidgetWindow::event (this=0x555556f69930, event=0x7fffffffc520)
at /run/build-runtime/qt6-qtbase/src/widgets/kernel/qwidgetwindow.cpp:292
#28 0x00007ffff77a167d in QApplicationPrivate::notify_helper (this=<optimized out>, receiver=0x555556f69930, e=0x7fffffffc520)
at /run/build-runtime/qt6-qtbase/src/widgets/kernel/qapplication.cpp:3301
#29 0x00007ffff55a5808 in QCoreApplication::notifyInternal2 (receiver=0x555556f69930, event=0x7fffffffc520)
at /run/build-runtime/qt6-qtbase/src/corelib/kernel/qcoreapplication.cpp:1106
#30 0x00007ffff55a5a7d in QCoreApplication::sendSpontaneousEvent (receiver=<optimized out>, event=<optimized out>)
at /run/build-runtime/qt6-qtbase/src/corelib/kernel/qcoreapplication.cpp:1560
#31 0x00007ffff5e02bd2 in QGuiApplicationPrivate::processMouseEvent (e=0x7fffdc001450)
at /run/build-runtime/qt6-qtbase/src/gui/kernel/qguiapplication.cpp:2483
#32 0x00007ffff5e6d29c in QWindowSystemInterface::sendWindowSystemEvents (flags=flags@entry=...)
at /run/build-runtime/qt6-qtbase/src/gui/kernel/qwindowsysteminterface.cpp:1113
#33 0x00007ffff5e6d4b0 in QWindowSystemInterface::flushWindowSystemEvents (flags=...)
at /run/build-runtime/qt6-qtbase/src/gui/kernel/qwindowsysteminterface.cpp:1082
#34 0x00007ffff55ff802 in QObject::event (this=0x555555ce2930, e=0x7fffe4002220) at /run/build-runtime/qt6-qtbase/src/corelib/kernel/qobject.cpp:1431
#35 0x00007ffff77a167d in QApplicationPrivate::notify_helper (this=<optimized out>, receiver=0x555555ce2930, e=0x7fffe4002220)
at /run/build-runtime/qt6-qtbase/src/widgets/kernel/qapplication.cpp:3301
#36 0x00007ffff55a5808 in QCoreApplication::notifyInternal2 (receiver=0x555555ce2930, event=0x7fffe4002220)
at /run/build-runtime/qt6-qtbase/src/corelib/kernel/qcoreapplication.cpp:1106
#37 0x00007ffff55a5a6d in QCoreApplication::sendEvent (receiver=<optimized out>, event=<optimized out>)
at /run/build-runtime/qt6-qtbase/src/corelib/kernel/qcoreapplication.cpp:1546
#38 0x00007ffff55a93d7 in QCoreApplicationPrivate::sendPostedEvents (receiver=0x0, event_type=0, data=0x555555cda050)
at /run/build-runtime/qt6-qtbase/src/corelib/kernel/qcoreapplication.cpp:1879
#39 0x00007ffff58c327f in postEventSourceDispatch (s=s@entry=0x555555d30a30)
at /run/build-runtime/qt6-qtbase/src/corelib/kernel/qeventdispatcher_glib.cpp:246
#40 0x00007ffff4f133f6 in g_main_dispatch (context=0x7fffec000f00) at ../glib/gmain.c:3357
#41 0x00007ffff4f740c7 in g_main_context_dispatch_unlocked (context=0x7fffec000f00) at ../glib/gmain.c:4208
#42 g_main_context_iterate_unlocked.isra.0 (context=context@entry=0x7fffec000f00, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>)
at ../glib/gmain.c:4273
#43 0x00007ffff4f12883 in g_main_context_iteration (context=0x7fffec000f00, may_block=1) at ../glib/gmain.c:4338
#44 0x00007ffff58c29b3 in QEventDispatcherGlib::processEvents (this=0x555555cda110, flags=...)
at /run/build-runtime/qt6-qtbase/src/corelib/kernel/qeventdispatcher_glib.cpp:399
#45 0x00007ffff55b31e3 in QEventLoop::exec (this=this@entry=0x7fffffffcb80, flags=..., flags@entry=...)
at /run/build-runtime/qt6-qtbase/src/corelib/global/qflags.h:77
#46 0x00007ffff55ae7c1 in QCoreApplication::exec () at /run/build-runtime/qt6-qtbase/src/corelib/global/qflags.h:77
#47 0x00005555556472a9 in ?? ()
#48 0x00007ffff4a2b188 in __libc_start_call_main (main=main@entry=0x555555646960, argc=argc@entry=1, argv=argv@entry=0x7fffffffd638)
at ../sysdeps/nptl/libc_start_call_main.h:58
#49 0x00007ffff4a2b24b in __libc_start_main_impl (main=0x555555646960, argc=1, argv=0x7fffffffd638, init=<optimized out>, fini=<optimized out>,
rtld_fini=<optimized out>, stack_end=0x7fffffffd628) at ../csu/libc-start.c:360
#50 0x0000555555649885 in ?? ()`

**Comment by Ortham** [comment]
> It didn't ask me to enable debug info but the output is here:

Sorry, for some reason the flatpak bundles that CI produces here don't include debug info, even though building and installing the bundle locally does include it...

Could you try the same again, but installing using `flatpak install --user --include-sdk --include-debug https://dl.flathub.org/build-repo/185543/io.github.loot.loot.flatpakref` and running with `flatpak run --command=sh --devel io.github.loot.loot//test` instead?

**Comment by RacerBG** [comment]
@Ortham This is the result:

```
Starting program: /app/bin/LOOT
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/x86_64-linux-gnu/libthread_db.so.1".
Detected locale "C" with character encoding "ANSI_X3.4-1968", which is not UTF-8.
Qt depends on a UTF-8 locale, and has switched to "C.UTF-8" instead.
If this causes problems, reconfigure your locale. See the locale(1) manual
for more information.
[New Thread 0x7ffff1e8f6c0 (LWP 16)]
[New Thread 0x7fffea3f56c0 (LWP 17)]
[New Thread 0x7fffe9bf46c0 (LWP 18)]
[New Thread 0x7fffe92b36c0 (LWP 19)]
[New Thread 0x7fffe893c6c0 (LWP 20)]
[New Thread 0x7fffe15ff6c0 (LWP 21)]
[New Thread 0x7fffe0dfe6c0 (LWP 22)]
[New Thread 0x7fffd63ff6c0 (LWP 23)]
[New Thread 0x7fffd5bfe6c0 (LWP 24)]
[New Thread 0x7fffd53fd6c0 (LWP 25)]
[New Thread 0x7fffd4bfc6c0 (LWP 26)]
[New Thread 0x7fffaffff6c0 (LWP 27)]
[New Thread 0x7fffaf7fe6c0 (LWP 28)]
[New Thread 0x7fffaeffd6c0 (LWP 29)]
[New Thread 0x7fffae7fc6c0 (LWP 30)]
[New Thread 0x7fffadffb6c0 (LWP 31)]
[Thread 0x7fffadffb6c0 (LWP 31) exited]
[Thread 0x7fffae7fc6c0 (LWP 30) exited]
[Thread 0x7fffaeffd6c0 (LWP 29) exited]
[Thread 0x7fffaf7fe6c0 (LWP 28) exited]
[Thread 0x7fffaffff6c0 (LWP 27) exited]
[Thread 0x7fffd4bfc6c0 (LWP 26) exited]
QIODevice::read (QFile, "/home/georgi/.var/app/io.github.loot.loot/config/heroic/gog_store/installed.json"): device not open
QIODevice::read (QFile, "/home/georgi/.var/app/io.github.loot.loot/config/heroic/legendaryConfig/legendary/installed.json"): device not open
QIODevice::read (QFile, "/home/georgi/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary/installed.json"): device not open
QLayout::addChildLayout: layout QFormLayout "" already has a parent
[New Thread 0x7fffd4bfc6c0 (LWP 32)]
[New Thread 0x7fffaffff6c0 (LWP 33)]
[New Thread 0x7fffaf7fe6c0 (LWP 34)]
[New Thread 0x7fffaeffd6c0 (LWP 35)]
[New Thread 0x7fffadeff6c0 (LWP 36)]
[Thread 0x7fffadeff6c0 (LWP 36) exited]
[New Thread 0x7fffad6fe6c0 (LWP 37)]
[Thread 0x7fffad6fe6c0 (LWP 37) exited]
[New Thread 0x7fffacefd6c0 (LWP 38)]
[New Thread 0x7fffaccfc6c0 (LWP 39)]
[New Thread 0x7fffacafb6c0 (LWP 40)]
[New Thread 0x7fffac8fa6c0 (LWP 41)]
[New Thread 0x7fffac6f96c0 (LWP 42)]
[New Thread 0x7fffac4f86c0 (LWP 43)]
[New Thread 0x7fffac2f76c0 (LWP 44)]
[New Thread 0x7fff87fff6c0 (LWP 45)]
[New Thread 0x7fff87afb6c0 (LWP 46)]
[New Thread 0x7fff876fa6c0 (LWP 47)]
[New Thread 0x7fff872f96c0 (LWP 48)]
[New Thread 0x7fff86ef86c0 (LWP 49)]
[New Thread 0x7fff86af76c0 (LWP 51)]
[New Thread 0x7fff862f56c0 (LWP 52)]
[New Thread 0x7fff866f66c0 (LWP 50)]
[Thread 0x7fffaeffd6c0 (LWP 35) exited]
[New Thread 0x7fffad6fe6c0 (LWP 53)]
[New Thread 0x7fffadeff6c0 (LWP 54)]
[New Thread 0x7fffaeffd6c0 (LWP 55)]
[Thread 0x7fffad6fe6c0 (LWP 53) exited]

Thread 1 "LOOT" received signal SIGILL, Illegal instruction.
0x00005555558dcf62 in std::mersenne_twister_engine<unsigned long, 32ul, 624ul, 397ul, 31ul, 2567483615ul, 11ul, 4294967295ul, 7ul, 2636928640ul, 15ul, 4022730752ul, 18ul, 1812433253ul>::_M_gen_rand (this=0x555555ca9140 <ogdf::s_random>) at /usr/include/c++/14.2.0/bits/random.tcc:414
414               _UIntType __y = ((_M_x[__k] & __upper_mask)
```

**Comment by Ortham** [comment]
> This is the result:

That looks better, but what about the output from the `bt` command? Some of the first part of the output of `bt full` might also be useful, but there'll probably be a lot of it.

**Comment by RacerBG** [comment]
Sorry about that, here is the bt output:

```
#0  0x00005555558dcf62 in std::mersenne_twister_engine<unsigned long, 32ul, 624ul, 397ul, 31ul, 2567483615ul, 11ul, 4294967295ul, 7ul, 2636928640ul, 15ul, 4022730752ul, 18ul, 1812433253ul>::_M_gen_rand (this=0x555555ca9140 <ogdf::s_random>) at /usr/include/c++/14.2.0/bits/random.tcc:414
#1  0x00005555558dd0c5 in std::mersenne_twister_engine<unsigned long, 32ul, 624ul, 397ul, 31ul, 2567483615ul, 11ul, 4294967295ul, 7ul, 2636928640ul, 15ul, 4022730752ul, 18ul, 1812433253ul>::operator() (this=this@entry=0x555555ca9140 <ogdf::s_random>) at /usr/include/c++/14.2.0/bits/random.tcc:459
#2  0x00005555558dcaee in ogdf::randomSeed () at /run/build/OGDF/src/ogdf/basic/basic.cpp:124
#3  0x000055555590be6d in ogdf::LayerByLayerSweep::reduceCrossings (this=0x555556421a50, sugi=..., H=..., nCrossings=@0x7fffffffad60: 254)
at /run/build/OGDF/src/ogdf/layered/SugiyamaLayout.cpp:1215
#4  0x000055555590cf25 in ogdf::LayerByLayerSweep::reduceCrossings (this=<optimized out>, sugi=..., H=..., nCrossings=@0x7fffffffad60: 254)
at /run/build/OGDF/include/ogdf/layered/LayerByLayerSweep.h:67
#5  ogdf::SugiyamaLayout::reduceCrossings (this=this@entry=0x7fffffffad00, H=...) at /run/build/OGDF/src/ogdf/layered/SugiyamaLayout.cpp:1248
#6  0x000055555590e9a7 in ogdf::SugiyamaLayout::doCall (this=0x7fffffffad00, AG=..., umlCall=umlCall@entry=false, rank=...)
at /run/build/OGDF/src/ogdf/layered/SugiyamaLayout.cpp:903
#7  0x000055555590fcdb in ogdf::SugiyamaLayout::doCall (this=<optimized out>, AG=..., umlCall=umlCall@entry=false)
at /run/build/OGDF/src/ogdf/layered/SugiyamaLayout.cpp:840
#8  0x000055555590fd4b in ogdf::SugiyamaLayout::call (this=<optimized out>, AG=...) at /run/build/OGDF/src/ogdf/layered/SugiyamaLayout.cpp:834
#9  0x000055555569d8eb in loot::calculateGraphLayout (nodes=std::vector of length 1, capacity 1 = {...})
at /run/build/LOOT/src/gui/qt/groups_editor/layout.cpp:97
#10 0x00005555556999f1 in loot::GraphView::doLayout (this=this@entry=0x5555564313f0, nodePositions=std::vector of length 0, capacity 0)
at /run/build/LOOT/src/gui/qt/groups_editor/graph_view.cpp:367
#11 0x000055555569a2cf in loot::GraphView::setGroups (this=0x5555564313f0, masterlistGroups=std::vector of length 1, capacity 1 = {...},
userGroups=std::vector of length 1, capacity 1 = {...}, installedPluginGroups=std::set with 0 elements,
nodePositions=std::vector of length 0, capacity 0) at /run/build/LOOT/src/gui/qt/groups_editor/graph_view.cpp:164
#12 0x00005555556941d8 in loot::GroupsEditorDialog::setGroups (this=this@entry=0x55555659a170,
masterlistGroups=std::vector of length 1, capacity 1 = {...}, userGroups=std::vector of length 1, capacity 1 = {...},
installedPluginGroups=std::set with 0 elements, nodePositions=std::vector of length 0, capacity 0)
at /run/build/LOOT/src/gui/qt/groups_editor/groups_editor_dialog.cpp:82
#13 0x00005555556d8c21 in loot::MainWindow::on_actionOpenGroupsEditor_triggered (this=0x7fffffffcf70) at /run/build/LOOT/src/gui/qt/main_window.cpp:1613
#14 0x000055555564d92f in loot::MainWindow::qt_metacall (this=0x7fffffffcf70, _c=<optimized out>, _id=10, _a=0x7fffffffbbb0)
at /run/build/LOOT/_flatpak_build/LOOT_autogen/PO2JQEDBWN/moc_main_window.cpp:547
#15 0x00007ffff560e20a in doActivate<false> (sender=0x55555615ccb0, signal_index=7, argv=0x7fffffffbbb0)
at /run/build-runtime/qt6-qtbase/src/corelib/kernel/qobject.cpp:4164
#16 0x00007ffff5604387 in QMetaObject::activate (sender=sender@entry=0x55555615ccb0, m=m@entry=0x7ffff65d6f60 <QAction::staticMetaObject>,
local_signal_index=local_signal_index@entry=4, argv=argv@entry=0x7fffffffbbb0) at /run/build-runtime/qt6-qtbase/src/corelib/kernel/qobject.cpp:4198
#17 0x00007ffff62a5fb4 in QMetaObject::activate<void, bool> (sender=0x55555615ccb0, mo=0x7ffff65d6f60 <QAction::staticMetaObject>, local_signal_index=4,
--Type <RET> for more, q to quit, c to continue without paging--c
ret=0x0) at /run/build-runtime/qt6-qtbase/src/corelib/kernel/qobjectdefs.h:306
#18 QAction::triggered (this=this@entry=0x55555615ccb0, _t1=<optimized out>)
at /run/build-runtime/qt6-qtbase/src/gui/Gui_autogen/include/moc_qaction.cpp:372
#19 0x00007ffff62a91af in QAction::activate (this=0x55555615ccb0, event=<optimized out>) at /run/build-runtime/qt6-qtbase/src/gui/kernel/qaction.cpp:1104
#20 0x00007ffff79a2994 in QMenuPrivate::activateCausedStack (this=0x5555560fa820, causedStack=..., action=0x55555615ccb0, action_e=QAction::Trigger,
self=<optimized out>) at /run/build-runtime/qt6-qtbase/src/widgets/widgets/qmenu.cpp:1410
#21 0x00007ffff79ab950 in QMenuPrivate::activateAction (this=0x5555560fa820, action=0x55555615ccb0, action_e=QAction::Trigger, self=<optimized out>)
at /run/build-runtime/qt6-qtbase/src/widgets/widgets/qmenu.cpp:1492
#22 0x00007ffff7809a08 in QWidget::event (this=0x5555560f9890, event=0x7fffffffc270) at /run/build-runtime/qt6-qtbase/src/widgets/kernel/qwidget.cpp:9354
#23 0x00007ffff77a167d in QApplicationPrivate::notify_helper (this=this@entry=0x555555cd5290, receiver=receiver@entry=0x5555560f9890,
e=e@entry=0x7fffffffc270) at /run/build-runtime/qt6-qtbase/src/widgets/kernel/qapplication.cpp:3301
#24 0x00007ffff77ac09b in QApplication::notify (this=<optimized out>, receiver=<optimized out>, e=0x7fffffffc270)
at /run/build-runtime/qt6-qtbase/src/widgets/kernel/qapplication.cpp:2778
#25 0x00007ffff55a5808 in QCoreApplication::notifyInternal2 (receiver=0x5555560f9890, event=0x7fffffffc270)
at /run/build-runtime/qt6-qtbase/src/corelib/kernel/qcoreapplication.cpp:1106
#26 0x00007ffff55a5a7d in QCoreApplication::sendSpontaneousEvent (receiver=<optimized out>, event=<optimized out>)
at /run/build-runtime/qt6-qtbase/src/corelib/kernel/qcoreapplication.cpp:1560
#27 0x00007ffff77aa64c in QApplicationPrivate::sendMouseEvent (receiver=0x5555560f9890, event=event@entry=0x7fffffffc270, alienWidget=<optimized out>,
nativeWidget=0x5555560f9890, buttonDown=buttonDown@entry=0x7ffff7de59f0 <qt_button_down>, lastMouseReceiver=..., spontaneous=true,
onlyDispatchEnterLeave=false) at /run/build-runtime/qt6-qtbase/src/widgets/kernel/qapplication.cpp:2359
#28 0x00007ffff781ebbb in QWidgetWindow::handleMouseEvent (this=0x5555563640f0, event=event@entry=0x7fffffffc520)
at /run/build-runtime/qt6-qtbase/src/widgets/kernel/qwidgetwindow.cpp:577
#29 0x00007ffff78211c8 in QWidgetWindow::event (this=0x5555563640f0, event=0x7fffffffc520)
at /run/build-runtime/qt6-qtbase/src/widgets/kernel/qwidgetwindow.cpp:292
#30 0x00007ffff77a167d in QApplicationPrivate::notify_helper (this=<optimized out>, receiver=0x5555563640f0, e=0x7fffffffc520)
at /run/build-runtime/qt6-qtbase/src/widgets/kernel/qapplication.cpp:3301
#31 0x00007ffff55a5808 in QCoreApplication::notifyInternal2 (receiver=0x5555563640f0, event=0x7fffffffc520)
at /run/build-runtime/qt6-qtbase/src/corelib/kernel/qcoreapplication.cpp:1106
#32 0x00007ffff55a5a7d in QCoreApplication::sendSpontaneousEvent (receiver=<optimized out>, event=<optimized out>)
at /run/build-runtime/qt6-qtbase/src/corelib/kernel/qcoreapplication.cpp:1560
#33 0x00007ffff5e02bd2 in QGuiApplicationPrivate::processMouseEvent (e=0x555557358ee0)
at /run/build-runtime/qt6-qtbase/src/gui/kernel/qguiapplication.cpp:2483
#34 0x00007ffff5e6d29c in QWindowSystemInterface::sendWindowSystemEvents (flags=flags@entry=...)
at /run/build-runtime/qt6-qtbase/src/gui/kernel/qwindowsysteminterface.cpp:1113
#35 0x00007ffff5e6d4b0 in QWindowSystemInterface::flushWindowSystemEvents (flags=...)
at /run/build-runtime/qt6-qtbase/src/gui/kernel/qwindowsysteminterface.cpp:1082
#36 0x00007ffff55ff802 in QObject::event (this=0x555555ce08e0, e=0x7fffe4002c90) at /run/build-runtime/qt6-qtbase/src/corelib/kernel/qobject.cpp:1431
#37 0x00007ffff77a167d in QApplicationPrivate::notify_helper (this=<optimized out>, receiver=0x555555ce08e0, e=0x7fffe4002c90)
at /run/build-runtime/qt6-qtbase/src/widgets/kernel/qapplication.cpp:3301
#38 0x00007ffff55a5808 in QCoreApplication::notifyInternal2 (receiver=0x555555ce08e0, event=0x7fffe4002c90)
at /run/build-runtime/qt6-qtbase/src/corelib/kernel/qcoreapplication.cpp:1106
#39 0x00007ffff55a5a6d in QCoreApplication::sendEvent (receiver=<optimized out>, event=<optimized out>)
at /run/build-runtime/qt6-qtbase/src/corelib/kernel/qcoreapplication.cpp:1546
#40 0x00007ffff55a93d7 in QCoreApplicationPrivate::sendPostedEvents (receiver=0x0, event_type=0, data=0x555555cd8000)
at /run/build-runtime/qt6-qtbase/src/corelib/kernel/qcoreapplication.cpp:1879
#41 0x00007ffff58c327f in postEventSourceDispatch (s=s@entry=0x555555d96f40)
at /run/build-runtime/qt6-qtbase/src/corelib/kernel/qeventdispatcher_glib.cpp:246
#42 0x00007ffff4f133f6 in g_main_dispatch (context=0x7fffec000f00) at ../glib/gmain.c:3357
#43 0x00007ffff4f740c7 in g_main_context_dispatch_unlocked (context=0x7fffec000f00) at ../glib/gmain.c:4208
#44 g_main_context_iterate_unlocked.isra.0 (context=context@entry=0x7fffec000f00, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>)
at ../glib/gmain.c:4273
#45 0x00007ffff4f12883 in g_main_context_iteration (context=0x7fffec000f00, may_block=1) at ../glib/gmain.c:4338
#46 0x00007ffff58c29b3 in QEventDispatcherGlib::processEvents (this=0x555555cd80c0, flags=...)
at /run/build-runtime/qt6-qtbase/src/corelib/kernel/qeventdispatcher_glib.cpp:399
#47 0x00007ffff55b31e3 in QEventLoop::exec (this=this@entry=0x7fffffffcb80, flags=..., flags@entry=...)
at /run/build-runtime/qt6-qtbase/src/corelib/global/qflags.h:77
#48 0x00007ffff55ae7c1 in QCoreApplication::exec () at /run/build-runtime/qt6-qtbase/src/corelib/global/qflags.h:77
#49 0x00007ffff5def97d in QGuiApplication::exec () at /run/build-runtime/qt6-qtbase/src/gui/kernel/qguiapplication.cpp:1993
#50 0x00007ffff77a15e9 in QApplication::exec () at /run/build-runtime/qt6-qtbase/src/widgets/kernel/qapplication.cpp:2568
#51 0x0000555555647089 in main (argc=<optimized out>, argv=<optimized out>) at /run/build/LOOT/src/gui/qt/main.cpp:198
```

**Comment by Ortham** [comment]
OK, that's very strange, the SIGILL is coming from inside GCC's C++ standard library implementation, and all that's being done to trigger it is using a default-constructed instance of `std::mt19937` to generate a new random number. I don't know why it would work for me but not for you, since the Flatpak means we're using the same version of GCC.

Since this is all happening within the standard library with no application inputs, it seems like it might be a GCC bug. I had a look at the relevant code in the latest commit in GCC's Git repository but it looks unchanged. Maybe it's hardware-specific? @RacerBG what's your CPU?

**Comment by RacerBG** [comment]
> OK, that's very strange, the SIGILL is coming from inside GCC's C++ standard library implementation, and all that's being done to trigger it is using a default-constructed instance of `std::mt19937` to generate a new random number. I don't know why it would work for me but not for you, since the Flatpak means we're using the same version of GCC.
> 
> Since this is all happening within the standard library with no application inputs, it seems like it might be a GCC bug. I had a look at the relevant code in the latest commit in GCC's Git repository but it looks unchanged. Maybe it's hardware-specific? [@RacerBG](https://github.com/RacerBG) what's your CPU?

AMD FX-8320 with the following instructions: MMX(+), SSE(1, 2, 3, 3S, 4.1, 4.2, 4A), XOP, AVX(1), FMA(3, 4), AES, CLMUL, AMD-V, x86-64

**Comment by Ortham** [comment]
Hmm, a fairly old CPU then, I suspect that when the code is built GCC is assuming support for an instruction that your CPU doesn't support. From comparing the CPUs I've tested on (an Intel i5-8400 and an AMD 9800X3D) against yours, I suspect it's either part of AVX2 or BMI2, though I don't see the target architecture being set anywhere so I'd expect it to default to `x86-64`, which shouldn't include those instruction sets.

Your best bet is probably to build LOOT yourself on your own machine and see if it works. It's probably easiest to built it as a Flatpak since that involves minimal build environment setup. The steps [here](https://github.com/loot/loot/blob/master/.github/workflows/ci.yml#L192-L216) should give you an idea of what's involved.

**Comment by RacerBG** [comment]
And for fun, here is the official Windows build of LOOT running through GE-Proton-Latest

![Image](https://github.com/user-attachments/assets/043b2090-2bfe-445d-a6bc-ba094078813b)

**Comment by Ortham** [comment]
Great, it took a while but I'm glad we found a workaround, though it means you'll need to build releases yourself, or as you've found you can use the Windows build through Wine. I'm slightly surprised that it works!

I'm going to close this as wontfix as I don't really want to put more effort into supporting CPUs that are more than 10 years old (everything newer should be fine if I'm right about it being AVX2 or BMI2), and it's relatively difficult to maintain without having the hardware myself. I've also removed the Flatpak mention from the issue title since I don't the issue is Flatpak-specific, it's just that's the only Linux builds we provide.

**Comment by RacerBG** [comment]
No problems, it's been a fun ride! 😃

I don't really plan to build LOOT myself though. As I mentioned earlier (somewhere) I don't use that feature. And if I need it the Windows build is working fine.

I really hope that the whole process brought some improvements to LOOT's debugging.

Kind regards,
Georgi

**Comment by Ortham** [comment]
> I really hope that the whole process brought some improvements to LOOT's debugging.

It was definitely a learning experience when it comes to debugging inside a Flatpak, at least I know what to do / look out for next time!
