### ISSUE TITLE
Some strings not translatable

### ISSUE THREAD

**Issue by WrinklyNinja** [loot/loot#385]
The main suspects are progress messages and tooltips, but everything modified since the last translation sweep should be checked.

The following cannot be translated by design:

* A few sentences in the First-Time Tips dialog (the first, the last, and I think the first two bullet points): this is because they contain inline HTML and I don't know of a neat way to handle that with the translations.
* Everything in the About dialog, it shouldn't be translated.
* The "Initialising user interface..." progress message, as it's displayed before the translations are loaded.
* Dropdowns with no selection have the default text "Select an item...". It's a string in the Polymer library's `paper-dropdown-menu`, which needs a suitable translation applied to its `label` property. There are multiple such elements in the interface though, so translating them all isn't neat and I prefer to wait to see if Polymer implements a more elegant solution.

**Comment by WrinklyNinja** [comment]
Done as of aee33ad8ed08cee05b46583b550191114afdea0d, I think.

**Comment by WrinklyNinja** [comment]
Re-opening this, as there are still some strings that aren't being translated. This may be because they're lacking `translate()` wrappers, or there may be a problem with the `l10n.js` script.

**Comment by WrinklyNinja** [comment]
Everything but the C++ progress messages has been fixed as of 21a643daa0d9ad3c8804f70d1ab1169056dad83b.

**Comment by steamb23** [comment]
i'm see your commit.
so, fix is available?

**Comment by WrinklyNinja** [comment]
> i'm see your commit.
> so, fix is available?

Not yet, there is still an issue with the progress messages that I want to fix before uploading another build.

**Comment by WrinklyNinja** [comment]
@steamb23: The fix is now available in the newest [snapshot build](https://www.dropbox.com/sh/scuvwwc6ovzagmd/AAD1TodBAwGQTuV1-4Z2d0sCa?dl=0).

**Comment by steamb23** [comment]
Found untranslated portion.
This has already been translated.
http://imgur.com/HxHCP3b

**Comment by WrinklyNinja** [comment]
> Found untranslated portion.
> But, this has already been translated.
> http://imgur.com/HxHCP3b

OK, fixed in 1ee2332192012435294b80e53fbe78c009cec75f.

> By the way, 'Latest LOOT thread.' and 'Your SKSE is up-to-date.' is not going translation?

They are messages from the masterlist, and can be translated in the masterlist, eg. [the Fallout NV masterlist](https://github.com/loot/falloutnv/blob/master/masterlist.yaml#L17). (The Skyrim masterlist is too big to link to like that.)

**Comment by steamb23** [comment]
oh..... That's enormous.
If I have time I'll try it.

or translate to get some help in skyrim/fallout korean community. :)

**Comment by WrinklyNinja** [comment]
> oh..... That's enormous.

Yes, it is. Even small contributions help though, so don't be worried about needing to do it all.

**Comment by WrinklyNinja** [comment]
Closing this, as I seem to have now caught all the strings. I've added info about those that intentionally cannot be translated to the issue description.
