### ISSUE TITLE
Card list gets scrolled when it shouldn't

### ISSUE THREAD

**Issue by pStyl3** [loot/loot#808]
Using "loot_0.11.0-23-g922fb20_dev.7z", it seems to be that in, like, every second attempt to enlarge or reduce the size of the opened metadata editor (by leftclicking on it's edge and moving it in one direction) the card list on LOOT's right side (and above the opened editor) get's scrolled up/down.

**Comment by WrinklyNinja** [comment]
I can replicate this at some positions in the list when enlarging the metadata editor.

**Comment by WrinklyNinja** [comment]
@pStyl3: This should be fixed in [this build](https://bintray.com/wrinklyninja/loot/loot/0.11.0-31-g6acac89_ui-fixes#files), can you verify?

**Comment by pStyl3** [comment]
Unfortunately I cant, the issue still occurs even with `loot_0.11.0-31-g6acac89_ui-fixes.7z`

**Comment by WrinklyNinja** [comment]
Darn, after you said that I was able to replicate it again. After another change I can't though, so please try [this build](https://bintray.com/wrinklyninja/loot/loot/0.11.0-32-g1d75c81_ui-fixes#files).

**Comment by pStyl3** [comment]
Now it's fixed for good. Great. 👍
