### ISSUE TITLE
LOOT 0.12.2 won't start

### ISSUE THREAD

**Issue by AndreF111** [loot/loot#873]
Release 0.12.2 isn't starting on my machine.
Windows 10. All upgrades installed.

I tried installing it on two drives. Tried both the installer and the 7zip versions... Same results.
Tried repairing the MSVC 2015 x86 redistributable. Didn't help.

The appdata LOOT folder is empty so I have no way to enable the debug log on the settings file.
Are the files in that folder supposed to be created during installation or when the app is first run?

**Comment by WrinklyNinja** [comment]
Does 0.12.1 work? What happens if you create the `settings.toml` file and enable debug logging in it as described [here](http://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html)?

**Comment by AndreF111** [comment]
I have created a text file, called it settings.toml and pasted enableDebugLogging = true into it.
No log was created when I tried to run the app.

0.12.1 works... but every time I run the app it behaves as if it's running for the first time.
If I click "Cancel" on the first run dialog I get this:
Error: Settings parsing failed. C:\Users\André\AppData\Local\LOOT\settings.toml could not be opened for parsing

**Comment by AndreF111** [comment]
These are the log files for 0.12.1

[LOOTDebugLog.txt](https://github.com/loot/loot/files/1704539/LOOTDebugLog.txt)
[CEFDebugLog.txt](https://github.com/loot/loot/files/1704540/CEFDebugLog.txt)

**Comment by AndreF111** [comment]
The latest version that works 100% on my machine is 0.11.0

**Comment by WrinklyNinja** [comment]
I bet this is because the TOML parser just uses standard streams and they don't support unicode paths (your username's `é`) on Windows...

What happens if you start 0.12.2 with the `--loot-data-path=C:\LOOT` (or anywhere not in your user directory) command line parameter?

**Comment by WrinklyNinja** [comment]
Also, try [this build](https://bintray.com/wrinklyninja/loot/download_file?file_path=loot_0.12.2-1-gc6eb940_fix-unicode-toml-path.7z), it should fix the issue.

**Comment by AndreF111** [comment]
That way it works.

**Comment by AndreF111** [comment]
Adding --loot-data-path=C:\LOOT to a shortcut fixes it, but the issue persists on that build you linked.

**Comment by WrinklyNinja** [comment]
Is the error still the same?

**Comment by WrinklyNinja** [comment]
Hmm, there must be something else not liking the path too.

**Comment by AndreF111** [comment]
These are the logs for the build you linked, when accessed with the command line parameter.

[CEFDebugLog.txt](https://github.com/loot/loot/files/1704930/CEFDebugLog.txt)
[LOOTDebugLog.txt](https://github.com/loot/loot/files/1704931/LOOTDebugLog.txt)

**Comment by JamesFreezeCZ** [comment]
same issue
my user folder is `Jakub Frýz`
but it works with `--loot-data-path=C:\LOOT`

**Comment by agharium** [comment]
Same issue.. my user folder has an "é" too.. 
But it works with `--loot-data-path=C:\LOOT` :)

**Comment by WrinklyNinja** [comment]
Ok, everyone try [this build](https://bintray.com/wrinklyninja/loot/download_file?file_path=loot_0.12.2-2-g457899a_fix-unicode-toml-path.7z), I can't replicate the issue any more with it.

**Comment by AndreF111** [comment]
Seems to be fixed for me.

**Comment by agharium** [comment]
Yup, it's fixed.

Thanks, bro.

**Comment by WrinklyNinja** [comment]
OK, fixed as of 457899a0d0c4710db70c6747d4d6109040fd9606, so closing this. I'll probably release 0.12.3 with the fix soon.
