### ISSUE TITLE
ERROR: Cannot read property "status" of undefined when starting LOOT

### ISSUE THREAD

**Issue by Shoshannah1** [loot/loot#915]
When trying to run Loot version 0.12.4 for original Skyrim I get the above error message.  It states there is no masterlist present.  When I try to download the masterlist it says "ERROR   Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information."

Log contents follow:
[LOOTDebugLog.txt](https://github.com/loot/loot/files/1816133/LOOTDebugLog.txt)

I have Windows 10 64 bit, fully updated.  Loot still works for Skyrim SE, but not for original Skyrim.  I looked in the appdata folder and do not see any .git folder, but there is one for Skyrim SE.  I tried uninstalling and reinstalling LOOT, same error.  Can anyone tell me how to fix this?

**Comment by Shoshannah1** [comment]
Addendum: I use NMM,  I tried manually downloading the masterlist and that did not work.   any help is appreciated.

**Comment by WrinklyNinja** [comment]
Well, neither the LOOT update checker nor the masterlist updater seem able to connect to GitHub... You say Skyrim SE works, have you tried updating its masterlist?

**Comment by Shoshannah1** [comment]
SE shows a masterlist but it also won't update.  Log is attached.

[LOOTDebugLog.txt](https://github.com/loot/loot/files/1820626/LOOTDebugLog.txt)

**Comment by dreamer1986** [comment]
I have the same problem on Win 10, so the easy fix for win7 from other reports doesn't work for me. I manually copied the Masterlist file and I got "Unknown: Git repository missing" in the masterlist revision and date. I've never seen this type of error since you launched LOOT I don't know how long ago...
[LOOTDebugLog.txt](https://github.com/loot/loot/files/1822615/LOOTDebugLog.txt)

**Comment by Shoshannah1** [comment]
I tried that.  Even did a full uninstall.  I still get "ERROR: Cannot read property"status" of undefined" when I start LOOT

**Comment by Shoshannah1** [comment]
Anyone else have an Idea?  And thanks for your suggestion dreamer1986

**Comment by WrinklyNinja** [comment]
Could it be a firewall thing? Your LOOT's unable to access GitHub at all, which isn't the same as the TLS issue Windows 7 users have been having.

**Comment by Shoshannah1** [comment]
I made sure LOOT is set to be able to get through the firewall.  Is there some Github software I need?  Github does not show up in the application/programs list of my firewall.  

[LOOTDebugLog.txt](https://github.com/loot/loot/files/1834387/LOOTDebugLog.txt)

**Comment by WrinklyNinja** [comment]
> Is there some Github software I need? Github does not show up in the application/programs list of my firewall.

No, GitHub's just a website, if anything your firewall would be blocking outbound connections from LOOT.exe. Do you use a proxy? I'm not sure what else it could be.

**Comment by Shoshannah1** [comment]
No, I don't use a proxy.  I'm fresh out of ideas here.  Thanks for any suggestions.  Could there be some other file missing (besides the masterlist) it needs to connect to Github?

**Comment by WrinklyNinja** [comment]
> Could there be some other file missing (besides the masterlist) it needs to connect to Github?

Not that I know of.

**Comment by OscarKilo** [comment]
Any update on this?  I am having the same issue.  I am also not able to connect to Github.com on the same pc at all.  I'm sure the issues are connected.  Any help would be greatly appreciated!

**Comment by WrinklyNinja** [comment]
> I am also not able to connect to Github.com on the same pc at all. I'm sure the issues are connected

So how are you posting here, on another PC? If you can't even access GitHub through your browser, there's probably nothing that I can reasonably do to get LOOT to access it.

Otherwise, try the [latest build](https://bintray.com/wrinklyninja/loot/download_file?file_path=loot_0.12.5-25-ge41f579_dev.7z), see if it improves things for you.

**Comment by OscarKilo** [comment]
Exactly, another PC.  I'm convinced it's a security issue on my Alienware.  After speaking with Microsoft for over an hour, I'd say the issue isn't with LOOT completely.  But I am getting some errors like others I have read.  First thing for me is definitely getting my browser to connect to Github, if there are LOOT errors after that, I'll worry about it then.  Thanks for getting back so quick.

**Comment by WrinklyNinja** [comment]
This was due to a bug in the github-api library LOOT's update checker was using, fixed in 304555e3297411ba72d3d33a99a77d44a83d59b3.

**Comment by OscarKilo** [comment]
I'm still not able to connect to get hub.com. I'm completely baffled by it, and so is Microsoft because they haven't been able to help at all with it.

**Comment by WrinklyNinja** [comment]
Well, at least the next release of LOOT won't throw meaningless errors at you when it's unable to connect. 🤷‍♂️

**Comment by ElementalSon** [comment]
Late to the party, but I had the same issue today (25/10/2019) - running LOOT as administrator fixed it.

**Comment by RemRem11** [comment]
I fix this problem by verifying my files launching fallout 4 after that shut the game down and reinstall loot. That worked for me
